name: "Custom Cursor Release"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - name: convert for windows
        run: |
          Get-ChildItem -Path "cursors" -Filter *.zip | ForEach-Object {
            $folderPath = $_.FullName -replace '\.zip$', ''
            Expand-Archive -Path $_.FullName -DestinationPath $folderPath
          }
          pip install -r requirements.txt
          python convert.py
          Remove-Item -Path ./cursors/*.zip -Force
          Get-ChildItem -Path "cursors" -Directory | ForEach-Object {
            Compress-Archive -Path $_.FullName -DestinationPath "$($_.FullName).zip"
          }

      - uses: svenstaro/upload-release-action@master
        with:
          file: ./cursors/*.zip
          release_name: Catppuccin Cursors
          file_glob: true
