name: "Cursor release"

# on:
#   push:
#     tags:
#       - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: ls -la cursors/
      - name: Add zips to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./cursors/*.zip
